name: github pages

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
          cache-dependency-path: ./SheronW/yarn.lock

      # - name: Setup Git Talk Config
      #   working-directory: ./SheronW/src/theme/BlogPostPage
      #   run: echo "const config = {clientSecret:'${{ secrets.CLIENT_SECRET }}'};export { config };" > config.js

      - name: Build website
        working-directory: ./SheronW
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./SheronW/build
          cname: sheronw.xyz
          publish_branch: master
