name: stories notify
on:
  push:
    paths:
      - "stories/**"

jobs:
  post:
    runs-on: ubuntu-18.04
    steps:
      - name: Webhook POST Action
        uses: muinmomin/webhook-action@v1.0.0
        with:
          # URL of webhook to send post request to
          url: ${{ "https://maker.ifttt.com/trigger/stories_commit_received/with/key/" + secrets.IFTTT_KEY }}
          # JSON string of data to pass into request
          data: '{"value1": "${{github.event.head_commit.message}}"}'
